# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 19:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import outlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=outlay.models.file_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Invalid Extension!')]),
        ),
    ]
