# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 07:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import outlay.models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0002_auto_20180926_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=outlay.models.file_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Unsupported format.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
